import Header from "./components/Header";
import StatusCards from "./components/StatusCards";
import JobsTable from "./components/JobsTable";
import Timeline from "./components/Timeline";
import DownloadsPanel from "./components/DownloadsPanel";
import Logs from "./components/Logs";
import InputDialog from "./components/InputDialog";
import DashboardStats from "./components/DashboardStats";
import Footer from "./components/Footer";
import { useConnectorStore } from "../../store/connectorStore";

export default function Dashboard() {
    const pendingInput = useConnectorStore((s) => s.pendingInput);
    return (
        <div className="min-h-screen bg-slate-100">

            <div className="max-w-7xl mx-auto px-6 py-6 space-y-6">
                {/* Header */}
                <Header />

                  {/* Input Dialog */}
                <InputDialog key={pendingInput?.request_id ?? "none"} />

                {/* Status Cards */}
                <StatusCards />

                {/* Dashboard Stats Cards */}
                <DashboardStats />

                {/* Jobs */}

                <section className="bg-white rounded-xl shadow-sm border border-slate-200 p-5">

                    <div className="mb-4">
                        <h2 className="text-xl font-semibold text-slate-800">
                            Jobs
                        </h2>

                        <p className="text-sm text-slate-500">
                            Current and completed connector jobs
                        </p>
                    </div>

                    <JobsTable />

                </section>

                {/* Bottom Layout */}

                <div className="grid grid-cols-12 gap-6">

                    {/* Logs */}

                    <section className="col-span-12 xl:col-span-8 bg-white rounded-xl shadow-sm border border-slate-200 p-5">

                        <div className="mb-4">
                            <h2 className="text-xl font-semibold text-slate-800">
                                Activity Logs
                            </h2>

                            <p className="text-sm text-slate-500">
                                Live execution logs from connector and agents
                            </p>
                        </div>

                        <div className="h-[720px] overflow-auto">
                            <Logs />
                        </div>

                    </section>

                    {/* Right Panel */}

                    <div className="col-span-12 xl:col-span-4 space-y-6">

                        <section className="bg-white rounded-xl shadow-sm border border-slate-200 p-5">

                            <div className="mb-4">
                                <h2 className="text-xl font-semibold text-slate-800">
                                    Timeline
                                </h2>

                                <p className="text-sm text-slate-500">
                                    Recent connector activity
                                </p>
                            </div>

                            <div className="h-[320px] overflow-auto">
                                <Timeline />
                            </div>

                        </section>

                        <section className="bg-white rounded-xl shadow-sm border border-slate-200 p-5">

                            <div className="mb-4">
                                <h2 className="text-xl font-semibold text-slate-800">
                                    Downloads
                                </h2>

                                <p className="text-sm text-slate-500">
                                    Files generated by agents
                                </p>
                            </div>

                            <div className="h-[320px] overflow-auto">
                                <DownloadsPanel />
                            </div>

                        </section>

                    </div>

                </div>

                {/* Footer */}
                <Footer />
            </div>

        </div>
    );
}