version: "3.9"

services:

  ric-databridge-connector:

    image: ghcr.io/Ricengg/ric-databridge-connector:1.0.0

    container_name: ric-databridge-connector

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./data:/app/data
      - ./logs:/app/logs