version: "3.9"

services:

  aip-databextract-connector:

    image: ghcr.io/smbasha2024/aip-databextract-connector:1.0.4

    container_name: aip-databextract-connector

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./data:/app/data
      - ./logs:/app/logs