name: Build Desktop Applications

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4